---
swagger: "2.0"
info:
  description: "This is a server for Rlog-api"
  version: "1.0.5"
  title: "Swagger RLog" 


paths:
  /user/login:
    post:
      summary: "Login user after validation"
      description: ""
      parameters:
        - name : "Authorization"
          in : "header"
          type: "string"
          required: true
          description: "Access Token"
      responses: 
        201:
          description: "user logged in"
          schema: 
            $ref: "#/definitions/User"
        404:
          description: "unauthorized user"
  /user/invites:
    get:
      summary: "Invite user"
      description: ""
      responses: 
        201:
          description: "user invited"
definitions:
  User: 
    type: "object"
    required:
      - "name"
      - "emailId"
      - "avatar"
    properties:
      id :
        example: "c604765d-6eb8-41df-b960-a43202c2f01d" 
      name :
        type: string
        example: "User Name"
      emailId:
        type: string
        example: "name.lastname@zopsmart.com"
      image:
        type: string  
        example: "https://1h3.googleusercontent.com/a/AATXAJwS4j7VeVOtbysLHrjaD-xh99TRHu-kaHxmOC M=s96-c"             
      createdOn:
        type: string
        example: "2022-05-23T08:26:10.0002"
      updatedOn:
        type: string
        example: "2022-05-23T08:26:10.0002"
      userAccountDetails: 
        example: "[]"
