---
swagger: "2.0"
info:
  description: "This is a server for Rlog-api"
  version: "1.0.5"
  title: "Swagger RLog" 


paths:
  /user/login:
    post:
      summary: "Login user after validation"
      description: ""
      parameters:
        - name : "user"
          in: "body"
          schema:
            $ref: "./src/services/userService.ts"
      # - name : "name"
      #   in : "formData"
      #   description: "Name of User"
      #   required : true
      #   type: "string"
      # - name: "emailId"
      #   in : "formData"
      #   description: "Email id of User"
      #   required : true
      #   type: "string"        
      # - name: "avatar"
      #   in : "formData"
      #   description: "Avatar of User"
      #   required : true
      #   type: "string"        
      # - name: "userAccountDetails"
      #   in : "formData"
      #   description: "Account Details of User"
      #   required : false   
      #   type : any    
      responses: 
        201:
          description: "user logged in"
          
        404:
          description: "unauthorized user"
  /user/invites:
    get:
      summary: "Invite user"
      description: ""
      responses: 
        201:
          description: "user invited"
                    
